title: My brain dump site
email: johntskarbek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Im an Infrastructure Engineer at CA Technologies in the Agile Business Unit.
  Reading and using the latest and greatest of technology is what I want to be doing.
  Blogging is not something I do on any regular basis (and it shows).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jtslear.github.io" # the base hostname & protocol for your site
twitter_username: johntskarbek
github_username:  jtslear

reading_time:     true
words_per_minute: 200

menu:
  - title: 'Home'
    url: '/'
  - title: 'Github'
    url: 'http://github.com/jtslear'
  - title: 'About'
    url: '/about/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'

owner:
  name:           John T Skarbek
  site:           http://jtslear.github.io
  avatar:         images/avatar.jpg
  bio: >
    Im an Infrastructure Engineer at CA Technologies in the Agile Business Unit.
    Reading and using the latest and greatest of technology is what I want to be doing.
    Blogging is not something I do on any regular basis (and it shows).
  email:          johntskarbek@gmail.com
locale:      en_US
future:      true
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM

permalink:   /:categories/:title/

paginate: 5

titlecase: true

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "Gruntfile.js",
  "LICENSE",
  "README.md",
  "Rakefile",
  "less",
  "lib",
  "log",
  "node_modules",
  "package.json",
]

gems:
  - jekyll-paginate
