# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My brain dump site
email: johntskarbek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an Infrastructure Engineer at CA Technologies in the Agile Business Unit.
  Reading and using the latest and greatest of technology is what I want to be doing.
  Blogging is not something I do on any regular basis (and it shows).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jtslear.github.io" # the base hostname & protocol for your site
twitter_username: djscribblinni
github_username:  jtslear

# Build settings
markdown: kramdown
